import type { MartialArt, Duration } from './types';

export const MARTIAL_ARTS: MartialArt[] = [
  { name: 'Wrestling', image: 'https://picsum.photos/seed/wrestling/400/300', color: 'red' },
  { name: 'MMA', image: 'https://picsum.photos/seed/mma/400/300', color: 'orange' },
  { name: 'Karate', image: 'https://picsum.photos/seed/karate/400/300', color: 'red' },
  { name: 'Judo', image: 'https://picsum.photos/seed/judo/400/300', color: 'sky' },
  { name: 'Taekwondo', image: 'https://picsum.photos/seed/taekwondo/400/300', color: 'blue' },
  { name: 'Kung Fu', image: 'https://picsum.photos/seed/kungfu/400/300', color: 'amber' },
  { name: 'Brazilian Jiu-Jitsu', image: 'https://picsum.photos/seed/bjj/400/300', color: 'purple' },
  { name: 'Muay Thai', image: 'https://picsum.photos/seed/muaythai/400/300', color: 'rose' },
  { name: 'Aikido', image: 'https://picsum.photos/seed/aikido/400/300', color: 'teal' },
  { name: 'Krav Maga', image: 'https://picsum.photos/seed/kravmaga/400/300', color: 'slate' },
  { name: 'Boxing', image: 'https://picsum.photos/seed/boxing/400/300', color: 'fuchsia' },
  { name: 'Capoeira', image: 'https://picsum.photos/seed/capoeira/400/300', color: 'green' },
  { name: 'Wing Chun', image: 'https://picsum.photos/seed/wingchun/400/300', color: 'yellow' },
  { name: 'Hapkido', image: 'https://picsum.photos/seed/hapkido/400/300', color: 'cyan' },
  { name: 'Savate', image: 'https://picsum.photos/seed/savate/400/300', color: 'lime' },
  { name: 'Kendo', image: 'https://picsum.photos/seed/kendo/400/300', color: 'indigo' },
  { name: 'Sumo', image: 'https://picsum.photos/seed/sumo/400/300', color: 'pink' },
  { name: 'Systema', image: 'https://picsum.photos/seed/systema/400/300', color: 'gray' },
  { name: 'Kickboxing', image: 'https://picsum.photos/seed/kickboxing/400/300', color: 'lime' },
  { name: 'Jeet Kune Do', image: 'https://picsum.photos/seed/jkd/400/300', color: 'emerald' },
  { name: 'Silat', image: 'https://picsum.photos/seed/silat/400/300', color: 'cyan' },
  { name: 'Eskrima', image: 'https://picsum.photos/seed/eskrima/400/300', color: 'rose' },
  { name: 'Sambo', image: 'https://picsum.photos/seed/sambo/400/300', color: 'red' },
  { name: 'Ninjutsu', image: 'https://picsum.photos/seed/ninjutsu/400/300', color: 'slate' },
  { name: 'Tai Chi', image: 'https://picsum.photos/seed/taichi/400/300', color: 'sky' },
  { name: 'Lethwei', image: 'https://picsum.photos/seed/lethwei/400/300', color: 'amber' },
  { name: 'Vovinam', image: 'https://picsum.photos/seed/vovinam/400/300', color: 'violet' },
  { name: 'Kalarippayattu', image: 'https://picsum.photos/seed/kalari/400/300', color: 'yellow' },
  { name: 'Gatka', image: 'https://picsum.photos/seed/gatka/400/300', color: 'green' },
  { name: 'Shorinji Kempo', image: 'https://picsum.photos/seed/kempo/400/300', color: 'blue' },
  { name: 'Pankration', image: 'https://picsum.photos/seed/pankration/400/300', color: 'pink' },
  { name: 'Bartitsu', image: 'https://picsum.photos/seed/bartitsu/400/300', color: 'gray' },
  { name: 'Fencing', image: 'https://picsum.photos/seed/fencing/400/300', color: 'sky' },
  { name: 'Kyudo', image: 'https://picsum.photos/seed/kyudo/400/300', color: 'indigo' },
  { name: 'Jujutsu', image: 'https://picsum.photos/seed/jujutsu/400/300', color: 'purple' },
  { name: 'Kenjutsu', image: 'https://picsum.photos/seed/kenjutsu/400/300', color: 'slate' },
  { name: 'Dambe', image: 'https://picsum.photos/seed/dambe/400/300', color: 'amber' },
  { name: 'Bokator', image: 'https://picsum.photos/seed/bokator/400/300', color: 'emerald' },
];

export const DURATIONS: Duration[] = [
  { label: '3 Days', value: '3 days' },
  { label: '7 Days', value: '7 days' },
  { label: '15 Days', value: '15 days' },
  { label: '1 Month', value: '1 month' },
  { label: '3 Months', value: '3 months' },
  { label: '6 Months', value: '6 months' },
];